baseURL = 'https://thefriendlyskies.github.io'
languageCode = 'en-us'
title = 'The Friendly Skies'
theme = 'planes'
copyright = '© {year} The Friendly Skies. All rights reserved.'

[params]
  favicon = "/favicon.ico"
  meta_description = "something here lol"
  og = "/og.png"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Articles"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq/"
    weight = 3
  [[menu.main]]
    identifier = "donate"
    name = "Donate"
    url = "https://www.buymeacoffee.com/rositamic"
    weight = 4

