baseURL = 'https://thefriendlyskies.net'
languageCode = 'en-us'
title = 'The Friendly Skies'
theme = 'planes'
copyright = '© {year} The Friendly Skies. All rights reserved.'

[params]
  favicon = "/favicon.ico"
  meta_description = "This blog is about civil aviation, technical aspects of aircraft design, aerospace, my personal experiences with aviation and many more topics concerned with … yes, you guessed it, aviation!"
  og = "/og.png"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Articles"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "donate"
    name = "Donate"
    url = "https://www.buymeacoffee.com/rositamic"
    weight = 4

[module]
  [[module.mounts]]
    source = "static"
    target = "assets"
