baseURL = 'https://thefriendlyskies.github.io'
languageCode = 'en-us'
title = 'The Friendly Skies'
theme = 'planes'
copyright = '© {year} The Friendly Skies. All rights reserved.'

[params]
  favicon = "/favicon.ico"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq/"
    weight = 4

